 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo16-oo2-2020?serverTimezone=UTC
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: grupooo216@gmail.com
    password: ohhhcrrqqgwusncc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false